### PR TITLE
MLOps Update

### PR DESCRIPTION
**Pull request by Gift-Ojeabulu**
I added Link to top books, courses and tools for MLOps

### CODE REVIEW

**Comment by Nyandwi** [comment]
Hi Gift, thanks for contributing to the Complete ML Package by adding top resources in MLOPs. I have been thinking about adding an MLOps guide as a reference since MLOps is beyond the scope of the package. Nonetheless, I appreciate you adding those resources and I will incorporate some of them in the guide. Thanks!

**Comment by Ram124567** [comment]
Thank you

**Comment by Gift-Ojeabulu** [comment]
Hi Jean, Thanks for the kind words.

I think we can work on a comprehensive guide for MLOps together. For the moment we just need to get a structure on how to go about it, for the resources I think I can help.

**Comment by Nyandwi** [comment]
Hi Gift, thanks for offering to help with the guide. I will ping you when I start to work on it so we can collaborate.

**Comment by Ram124567** [comment]
Hi,
 thanks for that kind information

**Pull request closed without merging**
